print("Hello World!")
print("This is my first Python program.")
print("I am excited to learn Python!")
print("Let's start coding!")
print("Python is a versatile language.")
print("I can use Python for web development, data analysis, and more.")
print("I will practice every day to improve my skills.")
print("I will build projects to apply what I learn.")
print("I will share my knowledge with others.")         
